/*
 *
 *  Managed Data Structures
 *  Copyright © 2016 Hewlett Packard Enterprise Development Company LP.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the 
 *  Application containing code generated by the Library and added to the 
 *  Application during this compilation process under terms of your choice, 
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

package com.hpl.mds;

import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;


public interface ListField<RT extends ManagedRecord,T extends ManagedObject> extends Field<RT, ManagedList<T>> {
  
  public static <RT extends ManagedRecord, T extends ManagedObject> 
  ListField<RT,T> inHolding(RecordType<RT> recType, CharSequence name, ManagedType<T> eltType) {
    return eltType.inList().fieldIn(recType, name);
  }

  public static <RT extends ManagedRecord, T extends ManagedObject> 
  ListField<RT,T> findInHolding(RecordType<RT> recType, CharSequence name, ManagedType<T> eltType) {
    return eltType.inList().findFieldIn(recType, name);
  }
  
  public int size(RT record);
  public long longSize(RT record);


  public boolean contains(RT record, T o);

  public Iterable<T> elements(RT record);
  
  public Iterator<T> iterator(RT record);

  public boolean add(RT record, T e);

  public boolean remove(RT record, T o);

  public boolean addAll(RT record, int index, Collection<? extends T> c);

  public void clear(RT record);

  public T get(RT record, int index);

  public T set(RT record, int index, T element);

  public void add(RT record, int index, T element);

  public T remove(RT record, int index);

  public int indexOf(RT record, T o);

  public int lastIndexOf(RT record, T o);

  public ListIterator<T> listIterator(RT record);

  public ListIterator<T> listIterator(RT record, int index);

  public List<T> subList(RT record, int fromIndex, int toIndex);
  
}
