/*
 *
 *  Managed Data Structures
 *  Copyright © 2016 Hewlett Packard Enterprise Development Company LP.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the 
 *  Application containing code generated by the Library and added to the 
 *  Application during this compilation process under terms of your choice, 
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

package com.hpl.mds;

import java.util.Iterator;


public interface SetField<RT extends ManagedRecord,T extends ManagedObject> extends Field<RT, ManagedSet<T>> {
  
  public static <RT extends ManagedRecord, T extends ManagedObject> 
  SetField<RT,T> inHolding(RecordType<RT> recType, CharSequence name, ManagedType<T> eltType) {
    return eltType.inSet().fieldIn(recType, name);
  }

  public static <RT extends ManagedRecord, T extends ManagedObject> 
  SetField<RT,T> findInHolding(RecordType<RT> recType, CharSequence name, ManagedType<T> eltType) {
    return eltType.inSet().findFieldIn(recType, name);
  }


  public int size(RT record);
  
  public long longSize(RT record);


  public boolean contains(RT record, T o);

  public Iterable<T> elements(RT record);
  
  public Iterator<T> iterator(RT record);

  public boolean add(RT record, T e);

  public boolean remove(RT record, T o);

  public void clear(RT record);


  
}
