/*
 *
 *  Managed Data Structures
 *  Copyright © 2016 Hewlett Packard Enterprise Development Company LP.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the 
 *  Application containing code generated by the Library and added to the 
 *  Application during this compilation process under terms of your choice, 
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

package test;

import com.hpl.mds.*;
import com.hpl.mds.annotations.*;
import static com.hpl.mds.MDS.*;
import java.util.List;
import java.util.Set;


@RecordSchema
interface Issue337Schema extends Comparable<Issue337>, Issue337a.Inner<String> {

  ManagedString uuid();

  static int compareTo(Issue337.Private self, Issue337 other) {
    return self.getUuid().compareTo(other.getUuid());
  }

  static List<Object[]> test(Issue337.Private self, List<Object[]> list) {
    return list;
  }
  // static Set<String> test(Issue337.Private self, Set<String> set) {
  //   return set;
  // }
  // static Set<Integer> test(Issue337.Private self, Set<Integer> set) {
  //   return set;
  // }
  static String[] test(Issue337.Private self, String[] s) {
    return s;
  }
}
