/*
 *
 *  Managed Data Structures
 *  Copyright © 2016 Hewlett Packard Enterprise Development Company LP.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the 
 *  Application containing code generated by the Library and added to the 
 *  Application during this compilation process under terms of your choice, 
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

package test;

import com.hpl.mds.annotations.*;
import com.hpl.mds.*;

@RecordSchema
@TypeName(name="mds-test-%1$s")
public interface PrivASchema {
  @Private int x();

  static void PrivA(PrivA.Constructing self) {
    self.setX(5);
    System.out.format("In PrivA ctor: %s%n", self);
  }

  @Private static void foo(PrivA.Private self) {
    self.incX(100);
    System.out.format("In PrivA.foo(): %s%n", self);
  }

  static int aVal(PrivA.Private self) {
    return self.getX();
  }

  static void doAStuff(PrivA.Private self) {
    self.foo();
  }

}
