/*
 *
 *  Managed Data Structures
 *  Copyright © 2016 Hewlett Packard Enterprise Development Company LP.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the 
 *  Application containing code generated by the Library and added to the 
 *  Application during this compilation process under terms of your choice, 
 *  provided you also meet the terms and conditions of the Application license.
 *
 */


package com.hpl.mds.task;

import java.util.HashSet;
import java.util.Set;

import com.hpl.mds.task.Task;


public class TaskContainer {

    // public static enum Operation {
    //     READ, WRITE
    // }

    public static TaskContainer setTaskContainer(Task task, Operation operation) {
        switch (operation) {
            case WRITE: 
                return new WriteTaskContainer(task);
            default: // READ
                return new TaskContainer(task);
        }
    }

    private Set<Task> allTasks;

    public TaskContainer(Task task) {
        allTasks = new HashSet<>();
        addTask(task);
    }

    public void addTask(Task task) {
        allTasks.add(task);
    }

    public Set<Task> allTasks() {
        return allTasks;
    }

} // end class TaskContainer

