/*
 *
 *  Managed Data Structures
 *  Copyright © 2016 Hewlett Packard Enterprise Development Company LP.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the 
 *  Application containing code generated by the Library and added to the 
 *  Application during this compilation process under terms of your choice, 
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

package com.hpl.erk.config.type;

import java.util.HashMap;
import java.util.Map;

import com.hpl.erk.config.PType;
import com.hpl.erk.types.TypeToken;

public class MapType<KT,VT> extends MappingType<KT, VT, Map<KT,VT>> {
  private static Generic GENERIC = null;
  
  
  @SuppressWarnings("rawtypes")
  public static class Generic extends MappingType.Generic<Map, Object, Object> {
    private Generic() {
      super(TypeToken.generic(Map.class));
    }
    
    public final <KT,VT> PType<Map<KT,VT>> of(PType<KT> keyType, PType<VT> valType) {
      return this.of(PType.<Map<KT,VT>>sig(), keyType, valType);
    }

    @Override
    public <T extends Map, P1, P2> PType<T> makeNewType(Sig<T> sig, TypeToken token, PType<P1> p1Type, PType<P2> p2Type) {
      @SuppressWarnings("unchecked")
      final PType<T> listType = (PType<T>)new MapType<>(p1Type, p2Type);
      return listType;
    }

  }

  protected MapType(PType<KT> keyType, PType<VT> valType) {
    super(generic(), generic().token(keyType, valType), keyType, valType);
  }
  
  @Override
  public Map<KT, VT> createEmpty() {
    return new HashMap<>();
  }
  
  public static Generic generic() {
    if (GENERIC == null) {
      GENERIC = new Generic();
    }
    return GENERIC;
  }
  
  public static <KT,VT> PType<Map<KT,VT>> of(PType<KT> keyType, PType<VT> valType) {
    return generic().of(keyType, valType);
  }

}
